swagger: '2.0'
info:
  version: '1.0'
  title: Messaging API
  description: 'Messaging Realtime Chat'
  contact: {}
host: localhost:8081
basePath: /messaging/v1
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /messages:
    post:
      description: This API for Create a New Message
      summary: New Message
      tags:
      - Misc
      operationId: MessagesPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/NewMessageRequest'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/NewMessageSuccessResponse'
          examples:
            application/json:
              code: 1000
              message: Delivered

  /messages/history:
    get:
      description: ' API for collect message that has been sent out'
      summary: Get Message History by senderId
      tags:
      - Misc
      operationId: MessagesInboxGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: sender_id
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/GetHistoryMessageSuccess'
          examples:
            application/json:
              code: 1000
              message: Success
              data:
              - id: 84
                sender_id: 1
                recepient_id: 10
                message: hello
                status: 2
                status_name: Delivered,
                created_date: "2019-05-20 06:21:33"
                last_updated: "2019-05-20 06:21:33"
              - id: 85
                sender_id: 1
                recepient_id: 10
                message: Yeah you
                status: 2
                status_name: Delivered,
                created_date: "2019-05-20 06:21:33"
                last_updated: "2019-05-20 06:21:33"
              - id: 86
                sender_id: 1
                recepient_id: 10
                message: How are you ?
                status: 2
                status_name: Delivered,
                created_date: "2019-05-20 06:21:33"
                last_updated: "2019-05-20 06:21:33"

definitions:
  NewMessageRequest:
    title: NewMessageRequest
    example:
      sender_id: 1
      recepient_id: 10
      text: Haloo
    type: object
    properties:
      sender_id:
        type: integer
        format: int32
      recepient_id:
        type: integer
        format: int32
      message:
        type: string
    required:
    - user_id
    - subject
    - to_user_id
    - text
  NewMessageSuccessResponse:
    title: NewMessageSuccessResponse
    example:
      code: 1000
      message: Delivered
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    required:
    - code
    - message
  GetHistoryMessageSuccess:
    title: GetMessageInboxSuccess
    example:
      code: 1000
      message: Success
      data:
      - id: 84
        sender_id: 1
        recepient_id: 10
        message: hello
        status: delivered
        created_date: '2019-05-20 06:21:33'
        last_updated: "2019-05-20 06:21:33"
      - id: 85
        sender_id: 1
        recepient_id: 10
        message: Yeah you
        status: delivered
        created_date: "2019-05-20 06:21:33"
        last_updated: "2019-05-20 06:21:33"
      - id: 86
        sender_id: 1
        recepient_id: 10
        message: How are you ?
        status: delivered
        created_date: "2019-05-20 06:21:33"
        last_updated: "2019-05-20 06:21:33"
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/Datum1'
    required:
    - code
    - message
    - data
  Datum1:
    title: Datum1
    type: object
    properties:
      id:
        example: 84
        type: integer
        format: int32
      sender_id:
        example: 1
        type: integer
        format: int32
      recepient_id:
        example: 1
        type: integer
        format: int32
      message:
        example: blablabla
        type: string
      status:
        example: received
        type: string
      created_at:
        example: "2019-05-20 06:21:33"
        type: string
      updated_at:
        example: "2019-05-20 06:21:45"
        type: string
    required:
    - id
    - sender_id
    - recepient_id
    - message
    - status
    - created_at
    - updated_at
tags:
- name: Misc
  description: ''
